---
sidebar: sidebar 
permalink: xcp/xcp-bp-hpc.html 
keywords: use case, gpfs, nfs 
summary: Nous avons utilisé NetApp XCP pour migrer les données de GPFS vers NFS afin que les GPU puissent traiter les données.  L’IA traite généralement les données d’un système de fichiers réseau. 
---
= Calcul haute performance vers ONTAP NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce cas d’utilisation est basé sur des demandes d’organisations de terrain.  Certains clients NetApp ont leurs données dans un environnement informatique hautes performances, qui fournit des analyses de données pour les modèles de formation et permet aux organismes de recherche d'obtenir un aperçu et une compréhension d'une grande quantité de données numériques.  Les ingénieurs de terrain NetApp ont besoin d'une procédure détaillée pour extraire les données du GPFS d'IBM vers NFS.  Nous avons utilisé NetApp XCP pour migrer les données de GPFS vers NFS afin que les GPU puissent traiter les données.  L’IA traite généralement les données d’un système de fichiers réseau.

Pour plus d'informations sur le cas d'utilisation du calcul haute performance vers ONTAP NFS, une démonstration enregistrée et les résultats des tests, consultez le https://blog.netapp.com/data-migration-xcp["Utilisation de XCP pour déplacer des données d'un lac de données et du calcul haute performance vers ONTAP NFS"^] blog.

Pour connaître les étapes détaillées du déplacement des données MapR-FS vers ONTAP NFS à l'aide de NetApp XCP, consultez l'annexe A : GPFS vers NFS - Étapes détailléeslink:https://docs.netapp.com/us-en/netapp-solutions-ai/data-analytics/bda-ai-introduction.html["ici"^] .
