---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-ps-consider.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: 'Il s"agit de la solution NetApp ONTAP pour la configuration, le renforcement et la validation d"un coffre-fort cybernétique basé sur ONTAP' 
---
= Considérations supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Des considérations supplémentaires doivent être prises en compte lors de la conception et du déploiement d’un coffre-fort cybernétique basé sur ONTAP .



== Considérations relatives au dimensionnement de la capacité

La quantité d'espace disque requise pour un volume de destination de coffre-fort cybernétique ONTAP dépend de divers facteurs, dont le plus important est le taux de variation des données dans le volume source.  La planification de sauvegarde et la planification d'instantanés sur le volume de destination affectent toutes deux l'utilisation du disque sur le volume de destination, et le taux de changement sur le volume source n'est probablement pas constant.  Il est judicieux de prévoir une capacité de stockage supplémentaire au-delà de celle requise pour s'adapter aux changements futurs du comportement de l'utilisateur final ou de l'application.

Le dimensionnement d'une relation pour 1 mois de rétention dans ONTAP nécessite de calculer les besoins de stockage en fonction de plusieurs facteurs, notamment la taille de l'ensemble de données principal, le taux de modification des données (taux de modification quotidien) et les économies de déduplication et de compression (le cas échéant).

Voici l’approche étape par étape :

La première étape consiste à connaître la taille du ou des volumes sources que vous protégez avec le coffre-fort numérique.  Il s’agit de la quantité de base de données qui sera initialement répliquée vers la destination du coffre-fort informatique.  Ensuite, estimez le taux de variation quotidien de l’ensemble de données.  Il s’agit du pourcentage de données qui change chaque jour.  Il est essentiel de bien comprendre le caractère dynamique de vos données.

Par exemple:

* Taille du jeu de données principal = 5 To
* Taux de variation quotidien = 5 % (0,05)
* Efficacité de déduplication et de compression = 50 % (0,50)


Maintenant, passons en revue le calcul :

* Calculer le taux de variation des données quotidiennes :
+
`Changed data per day = 5000 * 5% = 250GB`

* Calculez le total des données modifiées sur 30 jours :
+
`Total changed data in 30 days = 250 GB * 30 = 7.5TB`

* Calculez le stockage total requis :
+
`TOTAL = 5TB + 7.5TB = 12.5TB`

* Appliquer les économies de déduplication et de compression :
+
`EFFECTIVE = 12.5TB * 50% = 6.25TB`



*Résumé des besoins de stockage*

* Sans efficacité : il faudrait *12,5 To* pour stocker 30 jours de données du coffre-fort informatique.
* Avec une efficacité de 50 % : il faudrait *6,25 To* de stockage après déduplication et compression.



NOTE: Les copies instantanées peuvent entraîner une surcharge supplémentaire en raison des métadonnées, mais celle-ci est généralement mineure.


NOTE: Si plusieurs sauvegardes sont effectuées par jour, ajustez le calcul en fonction du nombre de copies Snapshot effectuées chaque jour.


NOTE: Tenez compte de la croissance des données au fil du temps pour garantir que le dimensionnement est à l’épreuve du temps.



== Impact sur les performances du primaire/de la source

Étant donné que le transfert de données est une opération d’extraction, l’impact sur les performances du stockage principal peut varier en fonction de la charge de travail, du volume de données et de la fréquence des sauvegardes.  Cependant, l’impact global sur les performances du système principal est généralement modéré et gérable, car le transfert de données est conçu pour décharger les tâches de protection et de sauvegarde des données vers le système de stockage du coffre-fort informatique.  Lors de la configuration initiale de la relation et de la première sauvegarde complète, une quantité importante de données est transférée du système principal vers le système de coffre-fort cybernétique (le volume de SnapLock Compliance ).  Cela peut entraîner une augmentation du trafic réseau et de la charge d'E/S sur le système principal.  Une fois la sauvegarde complète initiale terminée, ONTAP n'a plus qu'à suivre et transférer les blocs qui ont changé depuis la dernière sauvegarde.  Cela entraîne une charge d’E/S beaucoup plus faible par rapport à la réplication initiale.  Les mises à jour incrémentielles sont efficaces et ont un impact minimal sur les performances du stockage principal.  Le processus de coffre-fort s'exécute en arrière-plan, ce qui réduit les risques d'interférence avec les charges de travail de production du système principal.

* S’assurer que le système de stockage dispose de suffisamment de ressources (CPU, mémoire et IOPS) pour gérer la charge supplémentaire atténue l’impact sur les performances.

