---
sidebar: sidebar 
permalink: automation/getting-started.html 
summary: 'L"automatisation des solutions NetApp permet au client d"automatiser le déploiement, la configuration et l"exécution de nombreuses tâches courantes d"infrastructure et d"application.' 
keywords: netapp, awx, tower, ansible tower, solutions, automation, ansible, getting, started 
---
= Premiers pas avec l'automatisation des solutions NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'automatisation des solutions NetApp offre simplicité et répétabilité pour de nombreuses tâches courantes utilisées par les solutions NetApp .

Avant d’exécuter une automatisation de solution, l’environnement doit être configuré pour la manière dont l’automatisation sera exécutée.  Il existe des options pour exécuter l'automatisation à partir de la ligne de commande ou via un outil tel qu'AWX ou tower.

Les sections suivantes décrivent les étapes nécessaires à la configuration de l’environnement pour chacun des environnements spécifiés.

.Configurer le nœud de contrôle Ansible pour les déploiements CLI sur RHEL / CentOS
[%collapsible%open]
====
. Exigences pour le nœud de contrôle Ansible :
+
.. Une machine RHEL/CentOS avec les packages suivants installés :
+
... Python3
... Pip3
... Ansible (version supérieure à 2.10.0)
... Git






Si vous disposez d'une nouvelle machine RHEL/CentOS sans les exigences ci-dessus installées, suivez les étapes ci-dessous pour configurer cette machine comme nœud de contrôle Ansible :

. Activer le référentiel Ansible pour RHEL-8/RHEL-7
+
.. Pour RHEL-8 (exécutez la commande ci-dessous en tant que root)
+
[source, cli]
----
subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms
----
.. Pour RHEL-7 (exécutez la commande ci-dessous en tant que root)
+
[source, cli]
----
subscription-manager repos --enable rhel-7-server-ansible-2.9-rpms
----


. Collez le contenu ci-dessous dans le terminal
+
[source, cli]
----
sudo yum -y install python3 >> install.log
sudo yum -y install python3-pip >> install.log
python3 -W ignore -m pip --disable-pip-version-check install ansible >> install.log
sudo yum -y install git >> install.log
----


====
.Configurer le nœud de contrôle Ansible pour les déploiements CLI sur Ubuntu / Debian
[%collapsible%open]
====
. Exigences pour le nœud de contrôle Ansible :
+
.. Une machine Ubuntu/Debian avec les packages suivants installés :
+
... Python3
... Pip3
... Ansible (version supérieure à 2.10.0)
... Git






Si vous disposez d'une nouvelle machine Ubuntu/Debian sans les exigences ci-dessus installées, suivez les étapes ci-dessous pour configurer cette machine comme nœud de contrôle Ansible :

. Collez le contenu ci-dessous dans le terminal
+
[source, cli]
----
sudo apt-get -y install python3 >> outputlog.txt
sudo apt-get -y install python3-pip >> outputlog.txt
python3 -W ignore -m pip --disable-pip-version-check install ansible >> outputlog.txt
sudo apt-get -y install git >> outputlog.txt
----


====
.Configurer Ansible Tower ou AWX pour les déploiements Tower / AWX
[%collapsible%open]
====
Cette section décrit les étapes requises pour configurer les paramètres dans AWX/Ansible Tower qui préparent l'environnement pour la consommation de solutions automatisées NetApp .

. Configurer l'inventaire.
+
.. Accédez à Ressources → Inventaires → Ajouter et cliquez sur Ajouter un inventaire.
.. Indiquez le nom et les détails de l’organisation et cliquez sur Enregistrer.
.. Dans la page Inventaires, cliquez sur les ressources d’inventaire que vous venez de créer.
.. S'il existe des variables d'inventaire, collez-les dans le champ des variables.
.. Accédez au sous-menu Groupes et cliquez sur Ajouter.
.. Indiquez le nom du groupe, copiez les variables du groupe (si nécessaire) et cliquez sur Enregistrer.
.. Cliquez sur le groupe créé, accédez au sous-menu Hôtes et cliquez sur Ajouter un nouvel hôte.
.. Fournissez le nom d'hôte et l'adresse IP de l'hôte, collez les variables d'hôte (si nécessaire) et cliquez sur Enregistrer.


. Créer des types d’informations d’identification.  Pour les solutions impliquant ONTAP, Element, VMware ou toute autre connexion de transport basée sur HTTPS, vous devez configurer le type d'informations d'identification pour qu'il corresponde aux entrées de nom d'utilisateur et de mot de passe.
+
.. Accédez à Administration → Types d’informations d’identification et cliquez sur Ajouter.
.. Fournissez le nom et la description.
.. Collez le contenu suivant dans la configuration d'entrée :




[listing]
----
fields:
- id: username
type: string
label: Username
- id: password
type: string
label: Password
secret: true
- id: vsadmin_password
type: string
label: vsadmin_password
secret: true
----
. Collez le contenu suivant dans la configuration de l'injecteur :


[listing]
----
extra_vars:
password: '{{ password }}'
username: '{{ username }}'
vsadmin_password: '{{ vsadmin_password }}'
----
. Configurer les informations d'identification.
+
.. Accédez à Ressources → Informations d’identification et cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation.
.. Sélectionnez le type d'informations d'identification correct ; si vous avez l'intention d'utiliser la connexion SSH standard, sélectionnez le type Machine ou sélectionnez le type d'informations d'identification personnalisé que vous avez créé.
.. Saisissez les autres détails correspondants et cliquez sur Enregistrer.


. Configurer le projet.
+
.. Accédez à Ressources → Projets et cliquez sur Ajouter.
.. Saisissez le nom et les détails de l'organisation.
.. Sélectionnez Git comme type d’informations d’identification de contrôle de source.
.. Collez l'URL de contrôle de source (ou l'URL de clonage git) correspondant à la solution spécifique.
.. En option, si l'URL Git est contrôlée par accès, créez et joignez les informations d'identification correspondantes dans les informations d'identification de contrôle de source.
.. Cliquez sur Enregistrer.


. Configurer le modèle de travail.
+
.. Accédez à Ressources → Modèles → Ajouter et cliquez sur Ajouter un modèle de travail.
.. Entrez le nom et la description.
.. Sélectionnez le type de travail ; Exécuter configure le système en fonction d'un playbook et Vérifier effectue une exécution à sec du playbook sans réellement configurer le système.
.. Sélectionnez l’inventaire, le projet et les informations d’identification correspondants pour le playbook.
.. Sélectionnez le playbook que vous souhaitez exécuter dans le cadre du modèle de tâche.
.. Habituellement, les variables sont collées pendant l'exécution.  Par conséquent, pour obtenir l'invite permettant de renseigner les variables lors de l'exécution, assurez-vous de cocher la case Invite au lancement correspondant au champ Variable.
.. Fournissez tous les autres détails requis et cliquez sur Enregistrer.


. Lancez le modèle de travail.
+
.. Accédez à Ressources → Modèles.
.. Cliquez sur le modèle souhaité, puis sur Lancer.
.. Remplissez toutes les variables si vous y êtes invité au lancement, puis cliquez à nouveau sur Lancer.




====
Pour plus d'informations, veuillez visiterlink:https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible/["Premiers pas avec l'automatisation des solutions NetApp et Ansible"]

Pour demander une automatisation, veuillez remplir lelink:https://github.com/NetAppDocs/netapp-solutions/issues/new?body=%5BRequest%20Automation%5D%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20["formulaire de demande d'automatisation"] .
